added gitattributes exclude tests from archive
symfony/acl-bundle pull request #25
Opened 2021-04-07 18:33 UTC by iamvar

2021-04-07 18:47 UTC, derrabus approved these changes

2021-07-04 18:15 UTC, Tobion requested changes
`/.github` is missing by now

2021-07-14 05:13 UTC, iamvar commented
> `/.github` is missing by now

Thanks, added

2021-07-14 05:30 UTC, OskarStark approved these changes

2021-07-14 13:10 UTC, chalasr approved these changes

2021-07-14 13:14 UTC, derrabus commented
Thank you @iamvar.

2021-07-14 13:14 UTC, merged